/**
 * Regenerates the bundled offline catalogue + artwork.
 * Run: `npm run gen:data`.
 *
 * Content (Arabic) comes from src/data/content.ts. Numeric bottle specs come
 * from the backend seed. Output: src/data/catalogue.ts, src/data/media.ts
 * (artwork inlined as data URIs) and public/media/**.
 */
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { BOTTLE_VARIANTS } from '../../backend/src/seed/bottleSizes';
import { IDEAS_AR, VARIANT_LABELS_AR } from '../src/data/content';
import type { IdeaDetail, Variant } from '../src/lib/types';

const here = dirname(fileURLToPath(import.meta.url));
const FRONTEND = resolve(here, '..');
const MEDIA = resolve(FRONTEND, 'public/media');
const SVG = 'image/svg+xml';

const esc = (s: string) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const FONT = "font-family=\"'Segoe UI',Tahoma,Arial,sans-serif\"";

// ------------------------------------------------------------------ data ----

const VARIANTS: Variant[] = BOTTLE_VARIANTS.map((v) => ({
  id: `var-${v.key}`,
  key: v.key,
  categoryKey: 'bottle',
  label: VARIANT_LABELS_AR[v.key] ?? v.label,
  materialType: v.materialType,
  volumeMl: v.volumeMl,
  heightMm: v.heightMm,
  diameterMm: v.diameterMm,
  region: v.region,
  typicalContents: v.typicalContents,
  isCommon: v.isCommon,
  sortOrder: v.sortOrder,
  notes: v.notes,
}));

const IDEAS: IdeaDetail[] = IDEAS_AR.map((idea) => ({
  id: `idea-${idea.slug}`,
  slug: idea.slug,
  title: idea.title,
  summary: idea.summary,
  difficulty: idea.difficulty,
  estimatedMinutes: idea.estimatedMinutes,
  minAge: idea.minAge,
  safetyNotes: idea.safetyNotes ?? '',
  source: idea.source,
  thumbnailUrl: `media/ideas/${idea.slug}-thumb.svg`,
  finalImageUrl: `media/ideas/${idea.slug}-final.svg`,
  model3dUrl: '',
  model3dPreviewUrl: `media/ideas/${idea.slug}-3d.svg`,
  tools: idea.tools.map((t, i) => ({
    id: `tool-${idea.slug}-${i}`,
    kind: t.kind,
    name: t.name,
    imageUrl: '',
    quantity: t.quantity ?? '١',
    optional: t.optional ?? false,
    note: t.note ?? '',
  })),
  steps: idea.steps.map((s, i) => ({
    stepNumber: i + 1,
    title: s.title,
    instruction: s.instruction,
    op: s.op,
    measure: s.measure ?? '',
    tip: s.tip ?? '',
    warning: s.warning ?? '',
  })),
  variantKeys: idea.variantKeys,
}));

mkdirSync(resolve(FRONTEND, 'src/data'), { recursive: true });
writeFileSync(
  resolve(FRONTEND, 'src/data/catalogue.ts'),
  `// GENERATED by scripts/build-data.ts — do not edit by hand.
// Regenerate with: npm run gen:data
import type { IdeaDetail, Variant } from '../lib/types';

export const VARIANTS: Variant[] = ${JSON.stringify(VARIANTS, null, 2)};

export const IDEAS: IdeaDetail[] = ${JSON.stringify(IDEAS, null, 2)};
`,
  'utf8',
);

// (step blueprints are drawn at runtime — see src/components/blueprintSvg.ts)

// ------------------------------------------------------------- product art ---
// A distinct illustration of each finished project. Not photos — placeholders
// meant to read at a glance; swap the -final/-thumb SVGs for real photos later.

const HUES = [150, 96, 205, 32, 172, 48, 262, 12, 122, 210];
const GREEN = '#3f8f57';
const WATER = '#6fb0c6';

/** Simple bottle silhouette outline centred on cx. */
function sil(cx: number, topY: number, h: number, w: number, line: string) {
  const nw = w * 0.32;
  const nh = h * 0.09;
  const sh = h * 0.1;
  const bh = h - nh - sh;
  const x = cx - w / 2;
  const r = Math.min(14, w * 0.14);
  return `<path d="M${cx - nw / 2} ${topY} h${nw} v${nh} L${x + w} ${topY + nh + sh} v${bh} q0 ${r} ${-r} ${r} h${-(w - 2 * r)} q${-r} 0 ${-r} ${-r} v${-bh} L${cx - nw / 2} ${topY + nh} z" fill="none" stroke="${line}" stroke-width="7" stroke-linejoin="round"/>`;
}

const leaf = (x: number, y: number, dir: number) =>
  `<path d="M${x} ${y} q${18 * dir} -14 ${34 * dir} -4 q${-16 * dir} 16 ${-34 * dir} 4 z" fill="${GREEN}"/>`;

const PRODUCT: Record<string, (line: string, accent: string) => string> = {
  'self-watering-planter': (line) => `
    <path d="M250 250h140v96q0 18 -18 18H268q-18 0 -18 -18z" fill="none" stroke="${line}" stroke-width="7" stroke-linejoin="round"/>
    <path d="M256 300q16 -12 32 0t32 0t32 0t20 -4" fill="none" stroke="${WATER}" stroke-width="6"/>
    <path d="M262 250l58 -70l58 70" fill="none" stroke="${line}" stroke-width="7" stroke-linejoin="round"/>
    <path d="M320 180v-64" stroke="${GREEN}" stroke-width="7" fill="none"/>
    ${leaf(320, 150, 1)}${leaf(320, 128, -1)}${leaf(320, 108, 1)}
    <path d="M320 182v70" stroke="${WATER}" stroke-width="4" stroke-dasharray="6 5" fill="none"/>`,
  'bird-feeder': (line, accent) => `
    <path d="M120 92h150" stroke="${line}" stroke-width="6"/>
    <path d="M196 92c-16 6 -16 26 0 32" fill="none" stroke="${accent}" stroke-width="6"/>
    ${sil(320, 128, 210, 96, line)}
    <path d="M244 300h152M260 330h120" stroke="${line}" stroke-width="7" stroke-linecap="round"/>
    <circle cx="266" cy="300" r="4" fill="${line}"/><circle cx="374" cy="300" r="4" fill="${line}"/>
    <path d="M280 300a14 12 0 0 1 26 0" fill="none" stroke="${accent}" stroke-width="5"/>
    <g fill="${accent}"><circle cx="300" cy="366" r="5"/><circle cx="316" cy="372" r="5"/><circle cx="332" cy="365" r="5"/><circle cx="322" cy="356" r="5"/></g>`,
  'pen-pot-organizer': (line, accent) => `
    <path d="M250 250h140v96q0 18 -18 18H268q-18 0 -18 -18z" fill="none" stroke="${line}" stroke-width="7" stroke-linejoin="round"/>
    <path d="M250 250q35 -16 70 0t70 0" fill="none" stroke="${line}" stroke-width="7"/>
    <g stroke-width="9" stroke-linecap="round">
      <path d="M276 250l-12 -84" stroke="${accent}"/>
      <path d="M304 250l6 -104" stroke="${line}"/>
      <path d="M330 250l-2 -70" stroke="${GREEN}"/>
      <path d="M356 250l16 -96" stroke="${accent}"/>
    </g>
    <circle cx="264" cy="164" r="6" fill="${accent}"/><circle cx="372" cy="152" r="6" fill="${accent}"/>`,
  'coin-bank': (line, accent) => `
    ${sil(320, 110, 250, 104, line)}
    <path d="M296 176h48" stroke="${line}" stroke-width="9" stroke-linecap="round"/>
    <g fill="none" stroke="${accent}" stroke-width="6"><circle cx="320" cy="140" r="20"/><circle cx="320" cy="140" r="9"/></g>
    <g fill="none" stroke="${accent}" stroke-width="5">
      <ellipse cx="320" cy="322" rx="34" ry="10"/><ellipse cx="320" cy="308" rx="34" ry="10"/><ellipse cx="320" cy="294" rx="30" ry="9"/>
    </g>`,
  'watering-can': (line, accent) => `
    <g transform="rotate(-22 320 240)">
      ${sil(340, 150, 190, 92, line)}
      <path d="M300 152c-30 -4 -30 40 0 44" fill="none" stroke="${accent}" stroke-width="7"/>
      <path d="M294 344h20" stroke="${line}" stroke-width="8"/>
    </g>
    <g stroke="${WATER}" stroke-width="5" stroke-linecap="round">
      <path d="M250 300l-16 40M266 306l-10 42M282 310l-4 44M298 312l2 44"/>
    </g>
    <path d="M232 372q10 -30 30 -4M270 372q10 -30 30 -4" fill="none" stroke="${GREEN}" stroke-width="7"/>`,
  'drip-irrigation-spike': (line, accent) => `
    <path d="M180 348q140 -60 280 0z" fill="url(#soil)" stroke="${line}" stroke-width="5"/>
    <g transform="rotate(180 320 240)">${sil(320, 130, 200, 88, line)}</g>
    <path d="M320 300v56" stroke="${line}" stroke-width="7"/>
    <path d="M406 340v-40" stroke="${GREEN}" stroke-width="7"/>${leaf(406, 300, 1)}${leaf(406, 282, -1)}
    <path d="M320 360c6 8 8 12 8 15a8 8 0 0 1 -16 0c0 -3 2 -7 8 -15z" fill="${WATER}"/>`,
  'kids-bowling-set': (line, accent) => `
    ${sil(300, 200, 150, 60, line)}${sil(348, 210, 150, 60, line)}
    ${sil(324, 250, 150, 60, line)}${sil(372, 250, 150, 60, line)}
    <circle cx="210" cy="356" r="30" fill="none" stroke="${accent}" stroke-width="7"/>
    <path d="M150 372q30 -30 40 -10" fill="none" stroke="${line}" stroke-width="4" stroke-dasharray="4 6"/>`,
  'wind-spinner': (line, accent) => `
    <path d="M320 74v20" stroke="${line}" stroke-width="6"/>
    <path d="M320 74c-14 4 -14 18 0 22" fill="none" stroke="${accent}" stroke-width="6"/>
    <path d="M320 96v40M320 300v40" stroke="${line}" stroke-width="7" stroke-linecap="round"/>
    <g fill="none" stroke="${line}" stroke-width="6">
      <path d="M320 140c-46 8 -46 42 0 40c46 -8 46 20 0 30c-46 8 -46 42 0 40c46 -8 46 20 0 30c-46 8 -46 42 0 40"/>
      <path d="M320 140c46 8 46 42 0 40c-46 -8 -46 20 0 30c46 8 46 42 0 40c-46 -8 -46 20 0 30c46 8 46 42 0 40"/>
    </g>
    <g stroke="${accent}" stroke-width="5"><path d="M232 150l14 8M246 150l-14 8"/><path d="M394 330l14 8M408 330l-14 8"/></g>`,
  'vertical-herb-garden': (line) => `
    <path d="M232 96v250M430 96v250" stroke="${line}" stroke-width="6"/>
    ${[130, 210, 290].map((y) => `
      <path d="M222 ${y}h198v46q0 8 -8 8H230q-8 0 -8 -8z" fill="none" stroke="${line}" stroke-width="7" stroke-linejoin="round"/>
      <path d="M300 ${y}h44" stroke="${line}" stroke-width="7"/>
      <path d="M320 ${y}v-26" stroke="${GREEN}" stroke-width="6"/>${leaf(320, y - 20, 1)}${leaf(320, y - 34, -1)}`).join('')}`,
  'phone-charging-holder': (line, accent) => `
    <path d="M232 110v300" stroke="${line}" stroke-width="6"/>
    <path d="M244 150h70v190h-90q-8 0 -8 -8v-70q0 -8 8 -8h20z" fill="none" stroke="${line}" stroke-width="7" stroke-linejoin="round"/>
    <rect x="270" y="210" width="70" height="130" rx="10" transform="rotate(10 305 275)" fill="none" stroke="${accent}" stroke-width="7"/>
    <rect x="282" y="224" width="46" height="96" rx="4" transform="rotate(10 305 275)" fill="${accent}" opacity="0.35"/>
    <path d="M244 176h-30v-16h-14" fill="none" stroke="${line}" stroke-width="6"/>`,
};

function productArt(slug: string, title: string, hue: number, stage: boolean) {
  const bg = stage ? `hsl(${hue} 22% 22%)` : `hsl(${hue} 42% 74%)`;
  const bg2 = stage ? `hsl(${hue} 24% 15%)` : `hsl(${hue} 34% 58%)`;
  const line = stage ? `hsl(${hue} 40% 82%)` : `hsl(${hue} 45% 22%)`;
  const accent = stage ? `hsl(${hue} 60% 74%)` : `hsl(${hue} 55% 40%)`;
  const draw = PRODUCT[slug] ?? (() => sil(320, 150, 220, 110, line));
  const band = stage
    ? ''
    : `<rect x="0" y="404" width="640" height="76" fill="hsl(${hue} 40% 22%)"/>
       <text x="320" y="452" fill="#fff" ${FONT} font-size="30" font-weight="700" text-anchor="middle" direction="rtl">${esc(title)}</text>`;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="640" height="480" viewBox="0 0 640 480">
  <defs>
    <linearGradient id="g" x1="0" y1="0" x2="0.3" y2="1"><stop offset="0" stop-color="${bg}"/><stop offset="1" stop-color="${bg2}"/></linearGradient>
    <pattern id="soil" width="12" height="12" patternUnits="userSpaceOnUse"><circle cx="3" cy="3" r="1.5" fill="${line}"/><circle cx="9" cy="8" r="1.5" fill="${line}"/></pattern>
  </defs>
  <rect width="640" height="480" fill="url(#g)"/>
  <ellipse cx="320" cy="392" rx="160" ry="24" fill="rgba(0,0,0,0.14)"/>
  <g stroke-linecap="round">${draw(line, accent)}</g>
  ${band}
</svg>`;
}

// --------------------------------------------------------------- generate ----

const inlineMedia: Record<string, string> = {};
function write(rel: string, body: string, mime: string) {
  const target = resolve(MEDIA, rel);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, body, 'utf8');
  inlineMedia[`media/${rel}`] = `data:${mime},${encodeURIComponent(body)}`;
}

rmSync(MEDIA, { recursive: true, force: true });
for (const [i, idea] of IDEAS_AR.entries()) {
  const hue = HUES[i % HUES.length]!;
  write(`ideas/${idea.slug}-final.svg`, productArt(idea.slug, idea.title, hue, false), SVG);
  write(`ideas/${idea.slug}-thumb.svg`, productArt(idea.slug, idea.title, hue, false), SVG);
  write(`ideas/${idea.slug}-3d.svg`, productArt(idea.slug, idea.title, hue, true), SVG);
}

writeFileSync(
  resolve(FRONTEND, 'src/data/media.ts'),
  `// GENERATED by scripts/build-data.ts — do not edit by hand.
export const MEDIA: Record<string, string> = ${JSON.stringify(inlineMedia, null, 2)};
`,
  'utf8',
);

console.log(
  `catalogue.ts: ${VARIANTS.length} variants, ${IDEAS.length} ideas · ` +
    `media.ts: ${IDEAS_AR.length * 3} product images (step blueprints are runtime)`,
);
