// GENERATED by scripts/build-data.ts — do not edit by hand.
// Regenerate with: npx tsx scripts/build-data.ts
import type { IdeaDetail, Variant } from '../lib/types';

export const VARIANTS: Variant[] = [
  {
    "id": "var-pet-water-200ml",
    "key": "pet-water-200ml",
    "categoryKey": "bottle",
    "label": "قنينة مياه صغيرة جداً (٢٠٠ مل)",
    "materialType": "PET",
    "volumeMl": 200,
    "heightMm": 120,
    "diameterMm": 50,
    "region": "GLOBAL",
    "typicalContents": "water",
    "isCommon": true,
    "sortOrder": 10,
    "notes": "Kids / on-the-go size."
  },
  {
    "id": "var-pet-water-250ml",
    "key": "pet-water-250ml",
    "categoryKey": "bottle",
    "label": "قنينة مياه صغيرة (٢٥٠ مل)",
    "materialType": "PET",
    "volumeMl": 250,
    "heightMm": 140,
    "diameterMm": 52,
    "region": "GLOBAL",
    "typicalContents": "water",
    "isCommon": true,
    "sortOrder": 20,
    "notes": "Common single-serve size."
  },
  {
    "id": "var-pet-softdrink-330ml",
    "key": "pet-softdrink-330ml",
    "categoryKey": "bottle",
    "label": "قنينة مشروب غازي (٣٣٠ مل)",
    "materialType": "PET",
    "volumeMl": 330,
    "heightMm": 150,
    "diameterMm": 58,
    "region": "GLOBAL",
    "typicalContents": "soft drink",
    "isCommon": true,
    "sortOrder": 30,
    "notes": "Matches the 330 ml can format."
  },
  {
    "id": "var-pet-softdrink-350ml",
    "key": "pet-softdrink-350ml",
    "categoryKey": "bottle",
    "label": "قنينة مشروب غازي (٣٥٠ مل)",
    "materialType": "PET",
    "volumeMl": 350,
    "heightMm": 155,
    "diameterMm": 60,
    "region": "AMERICAS",
    "typicalContents": "soft drink",
    "isCommon": false,
    "sortOrder": 40,
    "notes": "US / Latin America format."
  },
  {
    "id": "var-pet-water-500ml",
    "key": "pet-water-500ml",
    "categoryKey": "bottle",
    "label": "قنينة مياه عادية (٥٠٠ مل)",
    "materialType": "PET",
    "volumeMl": 500,
    "heightMm": 210,
    "diameterMm": 66,
    "region": "GLOBAL",
    "typicalContents": "water",
    "isCommon": true,
    "sortOrder": 50,
    "notes": "The most common bottle worldwide."
  },
  {
    "id": "var-pet-water-600ml",
    "key": "pet-water-600ml",
    "categoryKey": "bottle",
    "label": "قنينة مياه (٦٠٠ مل)",
    "materialType": "PET",
    "volumeMl": 600,
    "heightMm": 230,
    "diameterMm": 66,
    "region": "GLOBAL",
    "typicalContents": "water",
    "isCommon": true,
    "sortOrder": 60,
    "notes": "Common in the US and parts of Asia."
  },
  {
    "id": "var-pet-sports-750ml",
    "key": "pet-sports-750ml",
    "categoryKey": "bottle",
    "label": "قنينة مياه رياضية (٧٥٠ مل)",
    "materialType": "PET",
    "volumeMl": 750,
    "heightMm": 250,
    "diameterMm": 70,
    "region": "GLOBAL",
    "typicalContents": "water",
    "isCommon": true,
    "sortOrder": 70,
    "notes": "Often with a sports cap."
  },
  {
    "id": "var-pet-water-1000ml",
    "key": "pet-water-1000ml",
    "categoryKey": "bottle",
    "label": "قنينة مياه كبيرة (١ لتر)",
    "materialType": "PET",
    "volumeMl": 1000,
    "heightMm": 300,
    "diameterMm": 85,
    "region": "GLOBAL",
    "typicalContents": "water",
    "isCommon": true,
    "sortOrder": 80,
    "notes": "One-litre size."
  },
  {
    "id": "var-pet-oil-1000ml",
    "key": "pet-oil-1000ml",
    "categoryKey": "bottle",
    "label": "قنينة زيت طعام (١ لتر)",
    "materialType": "PET",
    "volumeMl": 1000,
    "heightMm": 290,
    "diameterMm": 84,
    "region": "GLOBAL",
    "typicalContents": "cooking oil",
    "isCommon": true,
    "sortOrder": 85,
    "notes": "Rinse well before reuse."
  },
  {
    "id": "var-pet-water-1250ml",
    "key": "pet-water-1250ml",
    "categoryKey": "bottle",
    "label": "قنينة (١٫٢٥ لتر)",
    "materialType": "PET",
    "volumeMl": 1250,
    "heightMm": 310,
    "diameterMm": 90,
    "region": "EUROPE",
    "typicalContents": "soft drink",
    "isCommon": false,
    "sortOrder": 90,
    "notes": "Common for soft drinks in Europe."
  },
  {
    "id": "var-pet-water-1500ml",
    "key": "pet-water-1500ml",
    "categoryKey": "bottle",
    "label": "قنينة مياه (١٫٥ لتر)",
    "materialType": "PET",
    "volumeMl": 1500,
    "heightMm": 320,
    "diameterMm": 95,
    "region": "GLOBAL",
    "typicalContents": "water",
    "isCommon": true,
    "sortOrder": 100,
    "notes": "Family water size."
  },
  {
    "id": "var-pet-soda-2000ml",
    "key": "pet-soda-2000ml",
    "categoryKey": "bottle",
    "label": "قنينة مشروب غازي (٢ لتر)",
    "materialType": "PET",
    "volumeMl": 2000,
    "heightMm": 330,
    "diameterMm": 110,
    "region": "GLOBAL",
    "typicalContents": "soft drink",
    "isCommon": true,
    "sortOrder": 110,
    "notes": "Classic 2-litre soda bottle."
  },
  {
    "id": "var-pet-water-3000ml",
    "key": "pet-water-3000ml",
    "categoryKey": "bottle",
    "label": "قنينة مياه كبيرة (٣ لتر)",
    "materialType": "PET",
    "volumeMl": 3000,
    "heightMm": 360,
    "diameterMm": 130,
    "region": "GLOBAL",
    "typicalContents": "water",
    "isCommon": false,
    "sortOrder": 120,
    "notes": "Larger multi-serve bottle."
  },
  {
    "id": "var-pet-water-5000ml",
    "key": "pet-water-5000ml",
    "categoryKey": "bottle",
    "label": "قنينة مياه كبيرة (٥ لتر)",
    "materialType": "PET",
    "volumeMl": 5000,
    "heightMm": 300,
    "diameterMm": 190,
    "region": "GLOBAL",
    "typicalContents": "water",
    "isCommon": false,
    "sortOrder": 130,
    "notes": "Jerry-can style with handle."
  },
  {
    "id": "var-glass-soda-250ml",
    "key": "glass-soda-250ml",
    "categoryKey": "bottle",
    "label": "قنينة مشروب زجاجية (٢٥٠ مل)",
    "materialType": "GLASS",
    "volumeMl": 250,
    "heightMm": 200,
    "diameterMm": 55,
    "region": "GLOBAL",
    "typicalContents": "soft drink",
    "isCommon": false,
    "sortOrder": 140,
    "notes": "Returnable-style glass bottle."
  },
  {
    "id": "var-glass-beer-330ml",
    "key": "glass-beer-330ml",
    "categoryKey": "bottle",
    "label": "قنينة زجاجية (٣٣٠ مل)",
    "materialType": "GLASS",
    "volumeMl": 330,
    "heightMm": 230,
    "diameterMm": 60,
    "region": "GLOBAL",
    "typicalContents": "beer",
    "isCommon": true,
    "sortOrder": 150,
    "notes": "Long-neck glass bottle."
  },
  {
    "id": "var-glass-beer-500ml",
    "key": "glass-beer-500ml",
    "categoryKey": "bottle",
    "label": "قنينة زجاجية (٥٠٠ مل)",
    "materialType": "GLASS",
    "volumeMl": 500,
    "heightMm": 250,
    "diameterMm": 68,
    "region": "EUROPE",
    "typicalContents": "beer",
    "isCommon": true,
    "sortOrder": 160,
    "notes": "European half-litre bottle."
  },
  {
    "id": "var-glass-wine-750ml",
    "key": "glass-wine-750ml",
    "categoryKey": "bottle",
    "label": "قنينة زجاجية طويلة (٧٥٠ مل)",
    "materialType": "GLASS",
    "volumeMl": 750,
    "heightMm": 300,
    "diameterMm": 75,
    "region": "GLOBAL",
    "typicalContents": "wine",
    "isCommon": true,
    "sortOrder": 170,
    "notes": "Standard wine bottle."
  },
  {
    "id": "var-glass-spirits-700ml",
    "key": "glass-spirits-700ml",
    "categoryKey": "bottle",
    "label": "قنينة زجاجية (٧٠٠ مل)",
    "materialType": "GLASS",
    "volumeMl": 700,
    "heightMm": 285,
    "diameterMm": 78,
    "region": "GLOBAL",
    "typicalContents": "spirits",
    "isCommon": false,
    "sortOrder": 180,
    "notes": "Common spirits size outside the US."
  },
  {
    "id": "var-hdpe-milk-1000ml",
    "key": "hdpe-milk-1000ml",
    "categoryKey": "bottle",
    "label": "عبوة حليب (١ لتر)",
    "materialType": "HDPE",
    "volumeMl": 1000,
    "heightMm": 240,
    "diameterMm": 90,
    "region": "AMERICAS",
    "typicalContents": "milk",
    "isCommon": true,
    "sortOrder": 190,
    "notes": "Opaque HDPE jug with handle."
  },
  {
    "id": "var-hdpe-milk-2000ml",
    "key": "hdpe-milk-2000ml",
    "categoryKey": "bottle",
    "label": "عبوة حليب (٢ لتر)",
    "materialType": "HDPE",
    "volumeMl": 2000,
    "heightMm": 270,
    "diameterMm": 110,
    "region": "AMERICAS",
    "typicalContents": "milk",
    "isCommon": false,
    "sortOrder": 200,
    "notes": "Half-gallon style jug."
  },
  {
    "id": "var-hdpe-milk-3785ml",
    "key": "hdpe-milk-3785ml",
    "categoryKey": "bottle",
    "label": "عبوة حليب كبيرة (غالون)",
    "materialType": "HDPE",
    "volumeMl": 3785,
    "heightMm": 240,
    "diameterMm": 150,
    "region": "AMERICAS",
    "typicalContents": "milk",
    "isCommon": true,
    "sortOrder": 210,
    "notes": "US gallon milk jug with handle."
  },
  {
    "id": "var-pet-juice-250ml",
    "key": "pet-juice-250ml",
    "categoryKey": "bottle",
    "label": "قنينة عصير (٢٥٠ مل)",
    "materialType": "PET",
    "volumeMl": 250,
    "heightMm": 145,
    "diameterMm": 54,
    "region": "GLOBAL",
    "typicalContents": "juice",
    "isCommon": false,
    "sortOrder": 220,
    "notes": "Single-serve juice bottle."
  },
  {
    "id": "var-pet-juice-1000ml",
    "key": "pet-juice-1000ml",
    "categoryKey": "bottle",
    "label": "قنينة عصير (١ لتر)",
    "materialType": "PET",
    "volumeMl": 1000,
    "heightMm": 260,
    "diameterMm": 85,
    "region": "GLOBAL",
    "typicalContents": "juice",
    "isCommon": true,
    "sortOrder": 230,
    "notes": "Family juice bottle."
  },
  {
    "id": "var-can-energy-250ml",
    "key": "can-energy-250ml",
    "categoryKey": "can",
    "label": "علبة مشروب طاقة نحيلة (٢٥٠ مل)",
    "materialType": "ALUMINIUM",
    "volumeMl": 250,
    "heightMm": 134,
    "diameterMm": 53,
    "region": "GLOBAL",
    "typicalContents": "energy drink",
    "isCommon": true,
    "sortOrder": 10,
    "notes": "Narrow \"slim\" can format."
  },
  {
    "id": "var-can-soda-330ml",
    "key": "can-soda-330ml",
    "categoryKey": "can",
    "label": "علبة مشروب غازي عادية (٣٣٠ مل)",
    "materialType": "ALUMINIUM",
    "volumeMl": 330,
    "heightMm": 115,
    "diameterMm": 66,
    "region": "GLOBAL",
    "typicalContents": "soft drink",
    "isCommon": true,
    "sortOrder": 20,
    "notes": "The most common can worldwide."
  },
  {
    "id": "var-can-soda-355ml",
    "key": "can-soda-355ml",
    "categoryKey": "can",
    "label": "علبة مشروب غازي (٣٥٥ مل)",
    "materialType": "ALUMINIUM",
    "volumeMl": 355,
    "heightMm": 122,
    "diameterMm": 66,
    "region": "AMERICAS",
    "typicalContents": "soft drink",
    "isCommon": true,
    "sortOrder": 30,
    "notes": "US standard 12 oz can."
  },
  {
    "id": "var-can-beer-440ml",
    "key": "can-beer-440ml",
    "categoryKey": "can",
    "label": "علبة مشروب (٤٤٠ مل)",
    "materialType": "ALUMINIUM",
    "volumeMl": 440,
    "heightMm": 150,
    "diameterMm": 65,
    "region": "EUROPE",
    "typicalContents": "beer",
    "isCommon": false,
    "sortOrder": 40,
    "notes": "UK/EU pint-style can."
  },
  {
    "id": "var-can-tallboy-473ml",
    "key": "can-tallboy-473ml",
    "categoryKey": "can",
    "label": "علبة طويلة (٤٧٣ مل)",
    "materialType": "ALUMINIUM",
    "volumeMl": 473,
    "heightMm": 168,
    "diameterMm": 66,
    "region": "AMERICAS",
    "typicalContents": "beer",
    "isCommon": false,
    "sortOrder": 50,
    "notes": "Tall single-serve format."
  },
  {
    "id": "var-can-food-small-155ml",
    "key": "can-food-small-155ml",
    "categoryKey": "can",
    "label": "علبة معلّبات صغيرة (١٥٥ مل)",
    "materialType": "STEEL",
    "volumeMl": 155,
    "heightMm": 62,
    "diameterMm": 65,
    "region": "GLOBAL",
    "typicalContents": "tomato paste",
    "isCommon": true,
    "sortOrder": 60,
    "notes": "Short, wide tin — tomato paste / small goods."
  },
  {
    "id": "var-can-food-standard-425ml",
    "key": "can-food-standard-425ml",
    "categoryKey": "can",
    "label": "علبة معلّبات عادية (٤٢٥ مل)",
    "materialType": "STEEL",
    "volumeMl": 425,
    "heightMm": 110,
    "diameterMm": 73,
    "region": "GLOBAL",
    "typicalContents": "beans / vegetables",
    "isCommon": true,
    "sortOrder": 70,
    "notes": "The everyday size — beans, corn, tomatoes."
  },
  {
    "id": "var-can-food-large-850ml",
    "key": "can-food-large-850ml",
    "categoryKey": "can",
    "label": "علبة معلّبات كبيرة (٨٥٠ مل)",
    "materialType": "STEEL",
    "volumeMl": 850,
    "heightMm": 113,
    "diameterMm": 99,
    "region": "GLOBAL",
    "typicalContents": "tomatoes / legumes",
    "isCommon": false,
    "sortOrder": 80,
    "notes": "Family-size catering tin."
  },
  {
    "id": "var-can-coffee-tin-500ml",
    "key": "can-coffee-tin-500ml",
    "categoryKey": "can",
    "label": "علبة قهوة بغطا بلاستيك (٥٠٠ مل)",
    "materialType": "STEEL",
    "volumeMl": 500,
    "heightMm": 127,
    "diameterMm": 100,
    "region": "GLOBAL",
    "typicalContents": "coffee / formula",
    "isCommon": false,
    "sortOrder": 90,
    "notes": "Resealable plastic lid — good for a coin bank."
  }
];

export const IDEAS: IdeaDetail[] = [
  {
    "id": "idea-self-watering-planter",
    "slug": "self-watering-planter",
    "title": "مزهرية تسقي نفسها",
    "summary": "القنينة تنقصّ نصّين: الجزء العلوي مقلوب يحمل التراب والنبتة، والسفلي خزّان ماء، وفتيل قماش يوصل الماء للتراب.",
    "difficulty": "easy",
    "estimatedMinutes": 20,
    "minAge": 6,
    "safetyNotes": "القصّ يعمله شخص كبير. غطِّ الحافة المقصوصة بشريط لاصق.",
    "source": "الطريقة الشائعة (Red Ted Art · The Spruce Crafts · أدلة المكتبات)",
    "thumbnailUrl": "media/ideas/self-watering-planter-thumb.svg",
    "finalImageUrl": "media/ideas/self-watering-planter-final.svg",
    "model3dUrl": "",
    "model3dPreviewUrl": "",
    "tools": [
      {
        "id": "tool-self-watering-planter-0",
        "kind": "tool",
        "name": "مقص أو سكين ورق",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": "للقصّ — بيد شخص كبير."
      },
      {
        "id": "tool-self-watering-planter-1",
        "kind": "tool",
        "name": "قلم تحديد ومسطرة",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-self-watering-planter-2",
        "kind": "material",
        "name": "قنينة بلاستيك نظيفة",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": "٣٣٠ مل حتى ٥ لتر."
      },
      {
        "id": "tool-self-watering-planter-3",
        "kind": "material",
        "name": "شريط قماش قطني (من تيشيرت قديم)",
        "imageUrl": "",
        "quantity": "حسب المخطّط",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-self-watering-planter-4",
        "kind": "material",
        "name": "تراب زراعة",
        "imageUrl": "",
        "quantity": "كوب إلى كوبين",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-self-watering-planter-5",
        "kind": "material",
        "name": "نبتة صغيرة أو بذور",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-self-watering-planter-6",
        "kind": "material",
        "name": "شريط لاصق",
        "imageUrl": "",
        "quantity": "١",
        "optional": true,
        "note": "لتغطية الحافة."
      }
    ],
    "steps": [
      {
        "stepNumber": 1,
        "title": "نظّف القنينة",
        "instruction": "انزع الملصق، واغسل القنينة والغطا بالماء، وخلّيها تنشف تماماً.",
        "op": "clean",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 2,
        "title": "علّم خط القصّ",
        "instruction": "بالمسطرة، علّم خطاً دائرياً حوالين القنينة عند الارتفاع المبيّن بالمخطّط.",
        "op": "mark-cut",
        "measure": "planter-cut",
        "tip": "سنّد القلم على كومة كتب ودوّر القنينة ليطلع الخط مستقيماً.",
        "warning": ""
      },
      {
        "stepNumber": 3,
        "title": "اقصّ القنينة نصّين",
        "instruction": "شخص كبير يقصّ على الخط بالضبط. بيصير جزء علوي (بالغطا) وجزء سفلي.",
        "op": "cut",
        "measure": "planter-cut",
        "tip": "",
        "warning": "القصّ للكبار بس."
      },
      {
        "stepNumber": 4,
        "title": "أمّن الحافة",
        "instruction": "غطِّ حافة القصّ على القطعتين بشريط لاصق حتى ما تجرح.",
        "op": "seal-edge",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 5,
        "title": "ركّب الفتيل",
        "instruction": "اقصّ شريط القماش بالمقاس المبيّن، ومرّره من فتحة الغطا: نصفه داخل الجزء العلوي، ونصفه متدلٍّ تحت.",
        "op": "wick",
        "measure": "planter-wick",
        "tip": "إذا الفتحة صغيرة، افتح الغطا واعمل فيه ثقب ٥ ملّي بمسمار.",
        "warning": ""
      },
      {
        "stepNumber": 6,
        "title": "اقلب الجزء العلوي داخل السفلي",
        "instruction": "اقلب الجزء العلوي رأساً على عقب (الغطا للتحت) وحطّه داخل الجزء السفلي مثل القمع.",
        "op": "nest",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 7,
        "title": "حطّ التراب والنبتة",
        "instruction": "عبّي الجزء العلوي تراباً، وامسك الفتيل حتى ما ينطمّ، بعدين ازرع البذور أو النبتة.",
        "op": "fill-soil",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 8,
        "title": "عبّي الخزّان",
        "instruction": "ارفع الجزء العلوي وصبّ الماء في الجزء السفلي حتى الارتفاع المبيّن، بعدين رجّع الجزء العلوي مكانه.",
        "op": "fill-water",
        "measure": "planter-fill",
        "tip": "زوّد الماء كل كم يوم لمّا يقلّ.",
        "warning": ""
      }
    ],
    "variantKeys": [
      "pet-softdrink-330ml",
      "pet-softdrink-350ml",
      "pet-water-500ml",
      "pet-water-600ml",
      "pet-sports-750ml",
      "pet-water-1000ml",
      "pet-juice-1000ml",
      "pet-water-1250ml",
      "pet-water-1500ml",
      "pet-soda-2000ml",
      "pet-water-3000ml",
      "pet-water-5000ml",
      "hdpe-milk-1000ml",
      "hdpe-milk-2000ml",
      "hdpe-milk-3785ml"
    ]
  },
  {
    "id": "idea-bird-feeder",
    "slug": "bird-feeder",
    "title": "مطعم عصافير بالملاعق",
    "summary": "قنينة معلّقة، تمرّ فيها ملعقتان خشب كمسند، وفوق كل ملعقة فتحة صغيرة يطلع منها الحَب لمّا يقف العصفور.",
    "difficulty": "easy",
    "estimatedMinutes": 25,
    "minAge": 7,
    "safetyNotes": "الثقوب يعملها شخص كبير. علّقه بمكان بعيد عن القطط.",
    "source": "طريقة الملاعق الخشبية الشائعة (Instructables)",
    "thumbnailUrl": "media/ideas/bird-feeder-thumb.svg",
    "finalImageUrl": "media/ideas/bird-feeder-final.svg",
    "model3dUrl": "",
    "model3dPreviewUrl": "",
    "tools": [
      {
        "id": "tool-bird-feeder-0",
        "kind": "tool",
        "name": "سكين ورق",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": "للثقوب — بيد شخص كبير."
      },
      {
        "id": "tool-bird-feeder-1",
        "kind": "tool",
        "name": "قلم تحديد ومسطرة",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-bird-feeder-2",
        "kind": "material",
        "name": "قنينة نظيفة مع غطاها",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": "٧٥٠ مل حتى ٥ لتر."
      },
      {
        "id": "tool-bird-feeder-3",
        "kind": "material",
        "name": "ملعقتان خشب طويلتان",
        "imageUrl": "",
        "quantity": "٢",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-bird-feeder-4",
        "kind": "material",
        "name": "خيط أو دوبارة",
        "imageUrl": "",
        "quantity": "٤٠ سم",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-bird-feeder-5",
        "kind": "material",
        "name": "حَب عصافير",
        "imageUrl": "",
        "quantity": "كوب",
        "optional": false,
        "note": ""
      }
    ],
    "steps": [
      {
        "stepNumber": 1,
        "title": "نظّف القنينة ونشّفها",
        "instruction": "اغسل القنينة والغطا، انزع الملصق، وخلّيها تنشف تماماً.",
        "op": "clean",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 2,
        "title": "علّم مكان الملعقة الأولى",
        "instruction": "على جهتين متقابلتين، علّم نقطتين على الارتفاع المبيّن بالمخطّط.",
        "op": "mark-holes",
        "measure": "feeder-perch1",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 3,
        "title": "مرّر الملعقة الأولى",
        "instruction": "شخص كبير يعمل ثقبين صغيرين مكان العلامتين، ثم مرّر ملعقة الخشب حتى تطلع من الجهتين بالتساوي.",
        "op": "rod",
        "measure": "feeder-perch1",
        "tip": "",
        "warning": "الثقوب للكبار بس."
      },
      {
        "stepNumber": 4,
        "title": "مرّر الملعقة الثانية",
        "instruction": "علّم ثقبين آخرين فوق الأولى بالمسافة المبيّنة وبزاوية ربع دورة، ومرّر الملعقة الثانية.",
        "op": "rod",
        "measure": "feeder-perch2",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 5,
        "title": "افتح منافذ الحَب",
        "instruction": "فوق رأس كل ملعقة مباشرة، وسّع الثقب إلى فتحة بالقياس المبيّن ليخرج منها الحَب.",
        "op": "window",
        "measure": "feeder-opening",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 6,
        "title": "اعمل معلاقة",
        "instruction": "اعمل ثقبين صغيرين على جهتين قرب الغطا، مرّر خيط ٤٠ سم، واعمل عروة.",
        "op": "hanger",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 7,
        "title": "عبّي الحَب",
        "instruction": "صبّ حَب العصافير جوّا القنينة من فوق، وسكّر الغطا.",
        "op": "fill-seed",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 8,
        "title": "علّقه",
        "instruction": "علّق المطعم بغصن شجرة، بمكان تقدر تشوفه من الشبّاك وبعيد عن القطط.",
        "op": "use-hang",
        "measure": "",
        "tip": "",
        "warning": ""
      }
    ],
    "variantKeys": [
      "pet-sports-750ml",
      "pet-water-1000ml",
      "pet-oil-1000ml",
      "pet-juice-1000ml",
      "pet-water-1250ml",
      "pet-water-1500ml",
      "pet-soda-2000ml",
      "pet-water-3000ml",
      "pet-water-5000ml",
      "hdpe-milk-1000ml",
      "hdpe-milk-2000ml",
      "hdpe-milk-3785ml"
    ]
  },
  {
    "id": "idea-coin-bank",
    "slug": "coin-bank",
    "title": "حصّالة نقود",
    "summary": "قنينة كاملة فيها شقّ ضيّق على جنبها تنزّل منه القروش، وتفرّغها بفتح الغطا.",
    "difficulty": "easy",
    "estimatedMinutes": 15,
    "minAge": 6,
    "safetyNotes": "شقّ النقود يعمله شخص كبير.",
    "source": "الطريقة الشائعة (NOAA · All Free Crafts)",
    "thumbnailUrl": "media/ideas/coin-bank-thumb.svg",
    "finalImageUrl": "media/ideas/coin-bank-final.svg",
    "model3dUrl": "",
    "model3dPreviewUrl": "",
    "tools": [
      {
        "id": "tool-coin-bank-0",
        "kind": "tool",
        "name": "سكين ورق",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": "للشقّ — بيد شخص كبير."
      },
      {
        "id": "tool-coin-bank-1",
        "kind": "tool",
        "name": "قلم تحديد ومسطرة",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-coin-bank-2",
        "kind": "material",
        "name": "قنينة نظيفة مع غطاها",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-coin-bank-3",
        "kind": "material",
        "name": "ورق ملوّن ولاصق، أو دهان",
        "imageUrl": "",
        "quantity": "١",
        "optional": true,
        "note": "للتزيين."
      }
    ],
    "steps": [
      {
        "stepNumber": 1,
        "title": "نظّف القنينة ونشّفها",
        "instruction": "اغسل القنينة والغطا، انزع الملصق، ونشّفها. خلّي الغطا مسكّراً.",
        "op": "clean",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 2,
        "title": "علّم الشقّ",
        "instruction": "ضع القنينة على جنبها، وعلّم مستطيلاً رفيعاً على الجهة اللي لفوق بالمقاس المبيّن.",
        "op": "mark-slot",
        "measure": "bank-slot",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 3,
        "title": "اقصّ الشقّ",
        "instruction": "شخص كبير يقصّ على المستطيل بسكين الورق ليصير شقّاً.",
        "op": "slot",
        "measure": "bank-slot",
        "tip": "",
        "warning": "القصّ للكبار بس."
      },
      {
        "stepNumber": 4,
        "title": "جرّب قرشاً",
        "instruction": "جرّب تدخّل أكبر قرش من الشقّ. إذا كان ضيّقاً، وسّعه ١–٢ ملّي فقط.",
        "op": "coin-test",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 5,
        "title": "زيّنها",
        "instruction": "لفّ القنينة بورق ملوّن أو ادهنها، وخلّي الشقّ مكشوفاً.",
        "op": "decorate",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 6,
        "title": "ابدأ توفّر",
        "instruction": "نزّل القروش من الشقّ. لتفريغها، افتح الغطا فقط.",
        "op": "use-coins",
        "measure": "",
        "tip": "",
        "warning": ""
      }
    ],
    "variantKeys": [
      "pet-water-200ml",
      "pet-water-250ml",
      "pet-softdrink-330ml",
      "pet-softdrink-350ml",
      "pet-water-500ml",
      "pet-water-600ml",
      "pet-sports-750ml",
      "pet-water-1000ml",
      "pet-oil-1000ml",
      "pet-juice-250ml",
      "pet-juice-1000ml",
      "pet-water-1250ml",
      "pet-water-1500ml",
      "pet-soda-2000ml",
      "pet-water-3000ml",
      "pet-water-5000ml",
      "hdpe-milk-1000ml",
      "hdpe-milk-2000ml",
      "hdpe-milk-3785ml"
    ]
  },
  {
    "id": "idea-pen-pot-organizer",
    "slug": "pen-pot-organizer",
    "title": "علبة أقلام للمكتب",
    "summary": "قاع القنينة ينقصّ ليصير علبة تحمل الأقلام والمقص على المكتب.",
    "difficulty": "easy",
    "estimatedMinutes": 15,
    "minAge": 6,
    "safetyNotes": "القصّ يعمله شخص كبير. أمّن الحافة بطيّها للخارج أو بشريط.",
    "source": "الطريقة الشائعة (wikiHow · The Spruce Crafts)",
    "thumbnailUrl": "media/ideas/pen-pot-organizer-thumb.svg",
    "finalImageUrl": "media/ideas/pen-pot-organizer-final.svg",
    "model3dUrl": "",
    "model3dPreviewUrl": "",
    "tools": [
      {
        "id": "tool-pen-pot-organizer-0",
        "kind": "tool",
        "name": "مقص أو سكين ورق",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": "للقصّ — بيد شخص كبير."
      },
      {
        "id": "tool-pen-pot-organizer-1",
        "kind": "tool",
        "name": "قلم تحديد ومسطرة",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-pen-pot-organizer-2",
        "kind": "material",
        "name": "قنينة بلاستيك نظيفة",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": "٢٥٠ مل حتى ٢ لتر."
      },
      {
        "id": "tool-pen-pot-organizer-3",
        "kind": "material",
        "name": "شريط ملوّن أو دهان",
        "imageUrl": "",
        "quantity": "١",
        "optional": true,
        "note": ""
      }
    ],
    "steps": [
      {
        "stepNumber": 1,
        "title": "نظّف القنينة",
        "instruction": "اغسل القنينة، انزع الملصق، ونشّفها.",
        "op": "clean",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 2,
        "title": "حدّد الارتفاع",
        "instruction": "حطّ أطول قلم عندك جنب القنينة، وعلّم خطاً دائرياً على الارتفاع المبيّن بالمخطّط.",
        "op": "mark-cut",
        "measure": "pen-height",
        "tip": "دوّر القنينة على قلم ثابت ليطلع الخط منظّماً.",
        "warning": ""
      },
      {
        "stepNumber": 3,
        "title": "اقصّ الجزء العلوي",
        "instruction": "شخص كبير يقصّ على الخط بالضبط. احتفظ بالجزء السفلي.",
        "op": "cut-bottom",
        "measure": "pen-height",
        "tip": "",
        "warning": "القصّ للكبار بس."
      },
      {
        "stepNumber": 4,
        "title": "أمّن الحافة",
        "instruction": "اطوِ الحافة المقصوصة للخارج، أو غطّيها بشريط لاصق.",
        "op": "seal-edge",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 5,
        "title": "ثقب تصريف (اختياري)",
        "instruction": "إذا رح توقّف فيها فُرَشاً رطبة، اعمل ثقباً صغيراً بالقاع ليخرج الماء.",
        "op": "base-hole",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 6,
        "title": "زيّنها",
        "instruction": "لفّ العلبة بشريط ملوّن أو ادهنها وخلّيها تنشف.",
        "op": "decorate",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 7,
        "title": "استعملها",
        "instruction": "وقّف أقلامك وأدواتك جوّاها على المكتب.",
        "op": "use-pens",
        "measure": "",
        "tip": "",
        "warning": ""
      }
    ],
    "variantKeys": [
      "pet-water-250ml",
      "pet-softdrink-330ml",
      "pet-softdrink-350ml",
      "pet-juice-250ml",
      "pet-water-500ml",
      "pet-water-600ml",
      "pet-sports-750ml",
      "pet-water-1000ml",
      "pet-oil-1000ml",
      "pet-water-1250ml",
      "pet-water-1500ml",
      "pet-soda-2000ml",
      "hdpe-milk-1000ml"
    ]
  },
  {
    "id": "idea-can-pencil-organizer",
    "slug": "can-pencil-organizer",
    "title": "منظّم أقلام ومكتب",
    "summary": "علبة معدنية تنفتح من فوق وتتنضّف حافتها، تصير علبة تنظّم الأقلام وأدوات المكتب.",
    "difficulty": "easy",
    "estimatedMinutes": 15,
    "minAge": 6,
    "safetyNotes": "فتح الغطا وتنعيم الحافة يعملهم شخص كبير — حافة المعدن حادّة.",
    "source": "الطريقة الشائعة (wikiHow · The Spruce Crafts)",
    "thumbnailUrl": "media/ideas/can-pencil-organizer-thumb.svg",
    "finalImageUrl": "media/ideas/can-pencil-organizer-final.svg",
    "model3dUrl": "",
    "model3dPreviewUrl": "",
    "tools": [
      {
        "id": "tool-can-pencil-organizer-0",
        "kind": "tool",
        "name": "فتّاحة علب",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": "لفتح الغطا — بيد شخص كبير."
      },
      {
        "id": "tool-can-pencil-organizer-1",
        "kind": "tool",
        "name": "صنفرة أو شريط لاصق",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": "لتنعيم الحافة."
      },
      {
        "id": "tool-can-pencil-organizer-2",
        "kind": "material",
        "name": "علبة معدنية فاضية ونظيفة",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-can-pencil-organizer-3",
        "kind": "material",
        "name": "شريط ملوّن أو ورق لاصق",
        "imageUrl": "",
        "quantity": "١",
        "optional": true,
        "note": ""
      }
    ],
    "steps": [
      {
        "stepNumber": 1,
        "title": "نظّف العلبة",
        "instruction": "اشطف العلبة منيح واقلع الملصق، وخلّيها تنشف تماماً.",
        "op": "clean",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 2,
        "title": "افتح الغطا بالكامل",
        "instruction": "شخص كبير يفتح الغطا العلوي بالكامل بفتّاحة العلب حتى يصير فوهة مفتوحة.",
        "op": "open-top",
        "measure": "",
        "tip": "",
        "warning": "الفتح للكبار بس — حافة الغطا حادّة."
      },
      {
        "stepNumber": 3,
        "title": "نعّم الحافة",
        "instruction": "غطِّ حافة الفتحة بشريط لاصق سميك حوالين الدوران، أو انعّمها بالصنفرة حتى ما تجرح الإيد.",
        "op": "smooth-rim",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 4,
        "title": "زيّنها",
        "instruction": "لفّ العلبة بشريط ملوّن أو ورق لاصق من برّا.",
        "op": "decorate",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 5,
        "title": "استعملها",
        "instruction": "وقّف فيها أقلامك ومقصّك وأدواتك على المكتب.",
        "op": "use-pens",
        "measure": "",
        "tip": "",
        "warning": ""
      }
    ],
    "variantKeys": [
      "can-energy-250ml",
      "can-soda-330ml",
      "can-soda-355ml",
      "can-beer-440ml",
      "can-tallboy-473ml",
      "can-food-standard-425ml",
      "can-food-large-850ml",
      "can-coffee-tin-500ml"
    ]
  },
  {
    "id": "idea-can-punched-lantern",
    "slug": "can-punched-lantern",
    "title": "فانوس علبة بثقوب",
    "summary": "صفّ ثقوب صغيرة حوالين العلبة يطلع منها ضو الشمعة بشكل زخرفي جميل بالليل.",
    "difficulty": "medium",
    "estimatedMinutes": 30,
    "minAge": 8,
    "safetyNotes": "الثقب يعمله شخص كبير بمسمار ومطرقة. استعمل شمعة LED صغيرة بدل شمعة حقيقية إذا ممكن.",
    "source": "طريقة الفانوس المثقوب الشائعة (Instructables)",
    "thumbnailUrl": "media/ideas/can-punched-lantern-thumb.svg",
    "finalImageUrl": "media/ideas/can-punched-lantern-final.svg",
    "model3dUrl": "",
    "model3dPreviewUrl": "",
    "tools": [
      {
        "id": "tool-can-punched-lantern-0",
        "kind": "tool",
        "name": "مسمار ومطرقة",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": "للثقب — بيد شخص كبير."
      },
      {
        "id": "tool-can-punched-lantern-1",
        "kind": "tool",
        "name": "قلم تحديد",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-can-punched-lantern-2",
        "kind": "material",
        "name": "علبة معدنية فاضية ونظيفة",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-can-punched-lantern-3",
        "kind": "material",
        "name": "شمعة صغيرة أو LED",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-can-punched-lantern-4",
        "kind": "material",
        "name": "شريط ملوّن",
        "imageUrl": "",
        "quantity": "١",
        "optional": true,
        "note": ""
      }
    ],
    "steps": [
      {
        "stepNumber": 1,
        "title": "نظّف العلبة ونشّفها",
        "instruction": "اشطف العلبة واقلع الملصق. ممكن تعبّيها ماء وتحطّها بالفريزر ساعتين حتى يصير الثلج يثبّت الشكل ويسهّل الثقب.",
        "op": "clean",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 2,
        "title": "علّم مكان الثقوب",
        "instruction": "بالقلم، علّم نقاط الثقوب حوالين العلبة بالمكان المبيّن بالمخطّط — صفّ واحد أو أكتر بأي شكل يعجبك.",
        "op": "mark-holes",
        "measure": "can-lantern-holes",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 3,
        "title": "اثقب النقاط",
        "instruction": "شخص كبير يثقب كل نقطة بمسمار ومطرقة بلطف.",
        "op": "punch-holes",
        "measure": "can-lantern-holes",
        "tip": "",
        "warning": "الثقب للكبار بس، ويفضّل والعلبة فيها ثلج حتى ما تتعوّج."
      },
      {
        "stepNumber": 4,
        "title": "نعّم ولوّن الحافة",
        "instruction": "نعّم حافة الفتحة العلوية بشريط لاصق، ولوّن العلبة من برّا إذا حبّيت.",
        "op": "decorate",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 5,
        "title": "حطّ الشمعة",
        "instruction": "حطّ شمعة صغيرة أو LED جوّا العلبة واولعها بالليل ليطلع الضو من الثقوب.",
        "op": "fill-candle",
        "measure": "",
        "tip": "",
        "warning": ""
      }
    ],
    "variantKeys": [
      "can-energy-250ml",
      "can-soda-330ml",
      "can-soda-355ml",
      "can-beer-440ml",
      "can-tallboy-473ml",
      "can-food-standard-425ml"
    ]
  },
  {
    "id": "idea-can-succulent-planter",
    "slug": "can-succulent-planter",
    "title": "إصيص للنباتات الصغيرة",
    "summary": "علبة معدنية فيها ثقوب تصريف بالقاع، تصير إصيص نباتات صغيرة أو صبّار على طاولة المطبخ.",
    "difficulty": "easy",
    "estimatedMinutes": 15,
    "minAge": 7,
    "safetyNotes": "الثقب بالقاع يعمله شخص كبير.",
    "source": "طريقة أواني النباتات من علب معدنية (The Spruce Crafts)",
    "thumbnailUrl": "media/ideas/can-succulent-planter-thumb.svg",
    "finalImageUrl": "media/ideas/can-succulent-planter-final.svg",
    "model3dUrl": "",
    "model3dPreviewUrl": "",
    "tools": [
      {
        "id": "tool-can-succulent-planter-0",
        "kind": "tool",
        "name": "مسمار ومطرقة",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": "لثقب القاع — بيد شخص كبير."
      },
      {
        "id": "tool-can-succulent-planter-1",
        "kind": "material",
        "name": "علبة معدنية فاضية ونظيفة",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-can-succulent-planter-2",
        "kind": "material",
        "name": "تراب زراعة",
        "imageUrl": "",
        "quantity": "حسب حجم العلبة",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-can-succulent-planter-3",
        "kind": "material",
        "name": "نبتة صغيرة أو صبّار",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-can-succulent-planter-4",
        "kind": "material",
        "name": "دهان أو شريط ملوّن",
        "imageUrl": "",
        "quantity": "١",
        "optional": true,
        "note": ""
      }
    ],
    "steps": [
      {
        "stepNumber": 1,
        "title": "نظّف العلبة",
        "instruction": "اشطف العلبة، اقلع الملصق، وخلّيها تنشف. الغطا العلوي بيكون مفتوح أصلاً من الاستهلاك.",
        "op": "clean",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 2,
        "title": "علّم ثقوب التصريف",
        "instruction": "اقلب العلبة وعلّم ٢-٣ نقاط بقاعها بالمكان المبيّن بالمخطّط.",
        "op": "mark-holes",
        "measure": "can-planter-drain",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 3,
        "title": "اثقب التصريف",
        "instruction": "شخص كبير يثقب النقاط بمسمار ومطرقة ليصرف الماء الزايد.",
        "op": "punch-holes",
        "measure": "can-planter-drain",
        "tip": "",
        "warning": "الثقب للكبار بس."
      },
      {
        "stepNumber": 4,
        "title": "زيّنها",
        "instruction": "ادهن العلبة من برّا أو لفّها بشريط ملوّن، وخلّيها تنشف.",
        "op": "decorate",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 5,
        "title": "حطّ التراب والنبتة",
        "instruction": "عبّي العلبة تراباً لحد قبل الحافة بشوي، وازرع النبتة أو الصبّار.",
        "op": "fill-soil",
        "measure": "",
        "tip": "",
        "warning": ""
      }
    ],
    "variantKeys": [
      "can-food-small-155ml",
      "can-energy-250ml",
      "can-soda-330ml",
      "can-soda-355ml",
      "can-beer-440ml",
      "can-tallboy-473ml",
      "can-food-standard-425ml",
      "can-food-large-850ml"
    ]
  },
  {
    "id": "idea-can-wind-chime",
    "slug": "can-wind-chime",
    "title": "جرس هوا من علب معدنية",
    "summary": "كم علبة معلّقة بأطوال مختلفة، بتصدر رنين خفيف كل ما الهوا يحرّكها.",
    "difficulty": "medium",
    "estimatedMinutes": 30,
    "minAge": 8,
    "safetyNotes": "الثقب يعمله شخص كبير. حواف الفتحات لازم تتغطّى بشريط.",
    "source": "طريقة جرس الهوا من العلب الشائعة (Instructables · All Free Crafts)",
    "thumbnailUrl": "media/ideas/can-wind-chime-thumb.svg",
    "finalImageUrl": "media/ideas/can-wind-chime-final.svg",
    "model3dUrl": "",
    "model3dPreviewUrl": "",
    "tools": [
      {
        "id": "tool-can-wind-chime-0",
        "kind": "tool",
        "name": "مسمار ومطرقة",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": "للثقب — بيد شخص كبير."
      },
      {
        "id": "tool-can-wind-chime-1",
        "kind": "material",
        "name": "٤-٦ علب معدنية فاضية ونظيفة",
        "imageUrl": "",
        "quantity": "٤-٦",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-can-wind-chime-2",
        "kind": "material",
        "name": "خيط أو دوبارة",
        "imageUrl": "",
        "quantity": "حسب الطول",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-can-wind-chime-3",
        "kind": "material",
        "name": "عصاية خشب أو دائرة معدن للتعليق",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-can-wind-chime-4",
        "kind": "material",
        "name": "دهان أو شريط ملوّن",
        "imageUrl": "",
        "quantity": "١",
        "optional": true,
        "note": ""
      }
    ],
    "steps": [
      {
        "stepNumber": 1,
        "title": "نظّف العلب",
        "instruction": "اشطف كل العلب واقلع ملصقاتها، وخلّيها تنشف تماماً.",
        "op": "clean",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 2,
        "title": "علّم مكان ثقب التعليق",
        "instruction": "على كل علبة، علّم نقطة قرب الحافة العلوية بالمكان المبيّن بالمخطّط.",
        "op": "mark-holes",
        "measure": "can-chime-hang",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 3,
        "title": "اثقب كل علبة",
        "instruction": "شخص كبير يثقب نقطة التعليق بكل علبة بمسمار ومطرقة.",
        "op": "punch-holes",
        "measure": "can-chime-hang",
        "tip": "",
        "warning": "الثقب للكبار بس."
      },
      {
        "stepNumber": 4,
        "title": "مرّر خيوط التعليق",
        "instruction": "مرّر خيط بكل ثقب واربطه، بأطوال مختلفة شوي لكل علبة حتى تتلاقى وهي معلّقة.",
        "op": "hanger",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 5,
        "title": "زيّنها",
        "instruction": "لوّن العلب أو زيّنها بشريط ملوّن قبل ما تربطها.",
        "op": "decorate",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 6,
        "title": "علّقه",
        "instruction": "اربط كل خيوط العلب بعصاية أو دائرة، وعلّقه بمكان يوصله الهوا زي الشرفة أو الحديقة.",
        "op": "use-hang",
        "measure": "",
        "tip": "",
        "warning": ""
      }
    ],
    "variantKeys": [
      "can-energy-250ml",
      "can-soda-330ml",
      "can-soda-355ml",
      "can-beer-440ml",
      "can-tallboy-473ml",
      "can-food-standard-425ml"
    ]
  },
  {
    "id": "idea-can-coin-bank",
    "slug": "can-coin-bank",
    "title": "حصّالة نقود من علبة",
    "summary": "علبة قهوة أو معلّبات بغطا بلاستيك، فيها شقّ بالغطا تنزّل منه القروش، وتفتح الغطا لتفريغها.",
    "difficulty": "easy",
    "estimatedMinutes": 15,
    "minAge": 6,
    "safetyNotes": "شقّ الغطا يعمله شخص كبير.",
    "source": "طريقة حصّالة علبة القهوة الشائعة (All Free Crafts)",
    "thumbnailUrl": "media/ideas/can-coin-bank-thumb.svg",
    "finalImageUrl": "media/ideas/can-coin-bank-final.svg",
    "model3dUrl": "",
    "model3dPreviewUrl": "",
    "tools": [
      {
        "id": "tool-can-coin-bank-0",
        "kind": "tool",
        "name": "سكين حرفي أو مقص قوي",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": "للشقّ — بيد شخص كبير."
      },
      {
        "id": "tool-can-coin-bank-1",
        "kind": "tool",
        "name": "قلم تحديد ومسطرة",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-can-coin-bank-2",
        "kind": "material",
        "name": "علبة بغطا بلاستيك قابل لإعادة الإغلاق",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-can-coin-bank-3",
        "kind": "material",
        "name": "ورق ملوّن أو دهان",
        "imageUrl": "",
        "quantity": "١",
        "optional": true,
        "note": ""
      }
    ],
    "steps": [
      {
        "stepNumber": 1,
        "title": "نظّف العلبة والغطا",
        "instruction": "اشطف العلبة وغطاها البلاستيك، اقلع الملصق، ونشّفهم منيح.",
        "op": "clean",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 2,
        "title": "علّم الشقّ",
        "instruction": "على غطا العلبة البلاستيك، علّم مستطيلاً رفيعاً بالمقاس المبيّن بالمخطّط.",
        "op": "mark-slot",
        "measure": "can-bank-slot",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 3,
        "title": "اقصّ الشقّ",
        "instruction": "شخص كبير يقصّ على المستطيل بسكين حرفي ليصير شقّاً.",
        "op": "cut-slot",
        "measure": "can-bank-slot",
        "tip": "",
        "warning": "القصّ للكبار بس."
      },
      {
        "stepNumber": 4,
        "title": "زيّنها",
        "instruction": "لفّ العلبة بورق ملوّن أو ادهنها، وخلّي الشقّ مكشوفاً.",
        "op": "decorate",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 5,
        "title": "ابدأ توفّر",
        "instruction": "نزّل القروش من الشقّ. لتفريغها، افتح الغطا البلاستيك فقط.",
        "op": "use-coins",
        "measure": "",
        "tip": "",
        "warning": ""
      }
    ],
    "variantKeys": [
      "can-coffee-tin-500ml",
      "can-food-large-850ml"
    ]
  }
];
