// GENERATED by scripts/build-data.ts — do not edit by hand.
// Regenerate with: npm run gen:data
import type { IdeaDetail, Variant } from '../lib/types';

export const VARIANTS: Variant[] = [
  {
    "id": "var-pet-water-200ml",
    "key": "pet-water-200ml",
    "categoryKey": "bottle",
    "label": "قنينة مياه صغيرة جداً (٢٠٠ مل)",
    "materialType": "PET",
    "volumeMl": 200,
    "heightMm": 120,
    "diameterMm": 50,
    "region": "GLOBAL",
    "typicalContents": "water",
    "isCommon": true,
    "sortOrder": 10,
    "notes": "Kids / on-the-go size."
  },
  {
    "id": "var-pet-water-250ml",
    "key": "pet-water-250ml",
    "categoryKey": "bottle",
    "label": "قنينة مياه صغيرة (٢٥٠ مل)",
    "materialType": "PET",
    "volumeMl": 250,
    "heightMm": 140,
    "diameterMm": 52,
    "region": "GLOBAL",
    "typicalContents": "water",
    "isCommon": true,
    "sortOrder": 20,
    "notes": "Common single-serve size."
  },
  {
    "id": "var-pet-softdrink-330ml",
    "key": "pet-softdrink-330ml",
    "categoryKey": "bottle",
    "label": "قنينة مشروب غازي (٣٣٠ مل)",
    "materialType": "PET",
    "volumeMl": 330,
    "heightMm": 150,
    "diameterMm": 58,
    "region": "GLOBAL",
    "typicalContents": "soft drink",
    "isCommon": true,
    "sortOrder": 30,
    "notes": "Matches the 330 ml can format."
  },
  {
    "id": "var-pet-softdrink-350ml",
    "key": "pet-softdrink-350ml",
    "categoryKey": "bottle",
    "label": "قنينة مشروب غازي (٣٥٠ مل)",
    "materialType": "PET",
    "volumeMl": 350,
    "heightMm": 155,
    "diameterMm": 60,
    "region": "AMERICAS",
    "typicalContents": "soft drink",
    "isCommon": false,
    "sortOrder": 40,
    "notes": "US / Latin America format."
  },
  {
    "id": "var-pet-water-500ml",
    "key": "pet-water-500ml",
    "categoryKey": "bottle",
    "label": "قنينة مياه عادية (٥٠٠ مل)",
    "materialType": "PET",
    "volumeMl": 500,
    "heightMm": 210,
    "diameterMm": 66,
    "region": "GLOBAL",
    "typicalContents": "water",
    "isCommon": true,
    "sortOrder": 50,
    "notes": "The most common bottle worldwide."
  },
  {
    "id": "var-pet-water-600ml",
    "key": "pet-water-600ml",
    "categoryKey": "bottle",
    "label": "قنينة مياه (٦٠٠ مل)",
    "materialType": "PET",
    "volumeMl": 600,
    "heightMm": 230,
    "diameterMm": 66,
    "region": "GLOBAL",
    "typicalContents": "water",
    "isCommon": true,
    "sortOrder": 60,
    "notes": "Common in the US and parts of Asia."
  },
  {
    "id": "var-pet-sports-750ml",
    "key": "pet-sports-750ml",
    "categoryKey": "bottle",
    "label": "قنينة مياه رياضية (٧٥٠ مل)",
    "materialType": "PET",
    "volumeMl": 750,
    "heightMm": 250,
    "diameterMm": 70,
    "region": "GLOBAL",
    "typicalContents": "water",
    "isCommon": true,
    "sortOrder": 70,
    "notes": "Often with a sports cap."
  },
  {
    "id": "var-pet-water-1000ml",
    "key": "pet-water-1000ml",
    "categoryKey": "bottle",
    "label": "قنينة مياه كبيرة (١ لتر)",
    "materialType": "PET",
    "volumeMl": 1000,
    "heightMm": 300,
    "diameterMm": 85,
    "region": "GLOBAL",
    "typicalContents": "water",
    "isCommon": true,
    "sortOrder": 80,
    "notes": "One-litre size."
  },
  {
    "id": "var-pet-oil-1000ml",
    "key": "pet-oil-1000ml",
    "categoryKey": "bottle",
    "label": "قنينة زيت طعام (١ لتر)",
    "materialType": "PET",
    "volumeMl": 1000,
    "heightMm": 290,
    "diameterMm": 84,
    "region": "GLOBAL",
    "typicalContents": "cooking oil",
    "isCommon": true,
    "sortOrder": 85,
    "notes": "Rinse well before reuse."
  },
  {
    "id": "var-pet-water-1250ml",
    "key": "pet-water-1250ml",
    "categoryKey": "bottle",
    "label": "قنينة (١٫٢٥ لتر)",
    "materialType": "PET",
    "volumeMl": 1250,
    "heightMm": 310,
    "diameterMm": 90,
    "region": "EUROPE",
    "typicalContents": "soft drink",
    "isCommon": false,
    "sortOrder": 90,
    "notes": "Common for soft drinks in Europe."
  },
  {
    "id": "var-pet-water-1500ml",
    "key": "pet-water-1500ml",
    "categoryKey": "bottle",
    "label": "قنينة مياه (١٫٥ لتر)",
    "materialType": "PET",
    "volumeMl": 1500,
    "heightMm": 320,
    "diameterMm": 95,
    "region": "GLOBAL",
    "typicalContents": "water",
    "isCommon": true,
    "sortOrder": 100,
    "notes": "Family water size."
  },
  {
    "id": "var-pet-soda-2000ml",
    "key": "pet-soda-2000ml",
    "categoryKey": "bottle",
    "label": "قنينة مشروب غازي (٢ لتر)",
    "materialType": "PET",
    "volumeMl": 2000,
    "heightMm": 330,
    "diameterMm": 110,
    "region": "GLOBAL",
    "typicalContents": "soft drink",
    "isCommon": true,
    "sortOrder": 110,
    "notes": "Classic 2-litre soda bottle."
  },
  {
    "id": "var-pet-water-3000ml",
    "key": "pet-water-3000ml",
    "categoryKey": "bottle",
    "label": "قنينة مياه كبيرة (٣ لتر)",
    "materialType": "PET",
    "volumeMl": 3000,
    "heightMm": 360,
    "diameterMm": 130,
    "region": "GLOBAL",
    "typicalContents": "water",
    "isCommon": false,
    "sortOrder": 120,
    "notes": "Larger multi-serve bottle."
  },
  {
    "id": "var-pet-water-5000ml",
    "key": "pet-water-5000ml",
    "categoryKey": "bottle",
    "label": "قنينة مياه كبيرة (٥ لتر)",
    "materialType": "PET",
    "volumeMl": 5000,
    "heightMm": 300,
    "diameterMm": 190,
    "region": "GLOBAL",
    "typicalContents": "water",
    "isCommon": false,
    "sortOrder": 130,
    "notes": "Jerry-can style with handle."
  },
  {
    "id": "var-glass-soda-250ml",
    "key": "glass-soda-250ml",
    "categoryKey": "bottle",
    "label": "قنينة مشروب زجاجية (٢٥٠ مل)",
    "materialType": "GLASS",
    "volumeMl": 250,
    "heightMm": 200,
    "diameterMm": 55,
    "region": "GLOBAL",
    "typicalContents": "soft drink",
    "isCommon": false,
    "sortOrder": 140,
    "notes": "Returnable-style glass bottle."
  },
  {
    "id": "var-glass-beer-330ml",
    "key": "glass-beer-330ml",
    "categoryKey": "bottle",
    "label": "قنينة زجاجية (٣٣٠ مل)",
    "materialType": "GLASS",
    "volumeMl": 330,
    "heightMm": 230,
    "diameterMm": 60,
    "region": "GLOBAL",
    "typicalContents": "beer",
    "isCommon": true,
    "sortOrder": 150,
    "notes": "Long-neck glass bottle."
  },
  {
    "id": "var-glass-beer-500ml",
    "key": "glass-beer-500ml",
    "categoryKey": "bottle",
    "label": "قنينة زجاجية (٥٠٠ مل)",
    "materialType": "GLASS",
    "volumeMl": 500,
    "heightMm": 250,
    "diameterMm": 68,
    "region": "EUROPE",
    "typicalContents": "beer",
    "isCommon": true,
    "sortOrder": 160,
    "notes": "European half-litre bottle."
  },
  {
    "id": "var-glass-wine-750ml",
    "key": "glass-wine-750ml",
    "categoryKey": "bottle",
    "label": "قنينة زجاجية طويلة (٧٥٠ مل)",
    "materialType": "GLASS",
    "volumeMl": 750,
    "heightMm": 300,
    "diameterMm": 75,
    "region": "GLOBAL",
    "typicalContents": "wine",
    "isCommon": true,
    "sortOrder": 170,
    "notes": "Standard wine bottle."
  },
  {
    "id": "var-glass-spirits-700ml",
    "key": "glass-spirits-700ml",
    "categoryKey": "bottle",
    "label": "قنينة زجاجية (٧٠٠ مل)",
    "materialType": "GLASS",
    "volumeMl": 700,
    "heightMm": 285,
    "diameterMm": 78,
    "region": "GLOBAL",
    "typicalContents": "spirits",
    "isCommon": false,
    "sortOrder": 180,
    "notes": "Common spirits size outside the US."
  },
  {
    "id": "var-hdpe-milk-1000ml",
    "key": "hdpe-milk-1000ml",
    "categoryKey": "bottle",
    "label": "عبوة حليب (١ لتر)",
    "materialType": "HDPE",
    "volumeMl": 1000,
    "heightMm": 240,
    "diameterMm": 90,
    "region": "AMERICAS",
    "typicalContents": "milk",
    "isCommon": true,
    "sortOrder": 190,
    "notes": "Opaque HDPE jug with handle."
  },
  {
    "id": "var-hdpe-milk-2000ml",
    "key": "hdpe-milk-2000ml",
    "categoryKey": "bottle",
    "label": "عبوة حليب (٢ لتر)",
    "materialType": "HDPE",
    "volumeMl": 2000,
    "heightMm": 270,
    "diameterMm": 110,
    "region": "AMERICAS",
    "typicalContents": "milk",
    "isCommon": false,
    "sortOrder": 200,
    "notes": "Half-gallon style jug."
  },
  {
    "id": "var-hdpe-milk-3785ml",
    "key": "hdpe-milk-3785ml",
    "categoryKey": "bottle",
    "label": "عبوة حليب كبيرة (غالون)",
    "materialType": "HDPE",
    "volumeMl": 3785,
    "heightMm": 240,
    "diameterMm": 150,
    "region": "AMERICAS",
    "typicalContents": "milk",
    "isCommon": true,
    "sortOrder": 210,
    "notes": "US gallon milk jug with handle."
  },
  {
    "id": "var-pet-juice-250ml",
    "key": "pet-juice-250ml",
    "categoryKey": "bottle",
    "label": "قنينة عصير (٢٥٠ مل)",
    "materialType": "PET",
    "volumeMl": 250,
    "heightMm": 145,
    "diameterMm": 54,
    "region": "GLOBAL",
    "typicalContents": "juice",
    "isCommon": false,
    "sortOrder": 220,
    "notes": "Single-serve juice bottle."
  },
  {
    "id": "var-pet-juice-1000ml",
    "key": "pet-juice-1000ml",
    "categoryKey": "bottle",
    "label": "قنينة عصير (١ لتر)",
    "materialType": "PET",
    "volumeMl": 1000,
    "heightMm": 260,
    "diameterMm": 85,
    "region": "GLOBAL",
    "typicalContents": "juice",
    "isCommon": true,
    "sortOrder": 230,
    "notes": "Family juice bottle."
  }
];

export const IDEAS: IdeaDetail[] = [
  {
    "id": "idea-self-watering-planter",
    "slug": "self-watering-planter",
    "title": "مزهرية تسقي نفسها",
    "summary": "القنينة تنقصّ نصّين: الجزء العلوي مقلوب يحمل التراب والنبتة، والسفلي خزّان ماء، وفتيل قماش يوصل الماء للتراب.",
    "difficulty": "easy",
    "estimatedMinutes": 20,
    "minAge": 6,
    "safetyNotes": "القصّ يعمله شخص كبير. غطِّ الحافة المقصوصة بشريط لاصق.",
    "source": "الطريقة الشائعة (Red Ted Art · The Spruce Crafts · أدلة المكتبات)",
    "thumbnailUrl": "media/ideas/self-watering-planter-thumb.svg",
    "finalImageUrl": "media/ideas/self-watering-planter-final.svg",
    "model3dUrl": "",
    "model3dPreviewUrl": "",
    "tools": [
      {
        "id": "tool-self-watering-planter-0",
        "kind": "tool",
        "name": "مقص أو سكين ورق",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": "للقصّ — بيد شخص كبير."
      },
      {
        "id": "tool-self-watering-planter-1",
        "kind": "tool",
        "name": "قلم تحديد ومسطرة",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-self-watering-planter-2",
        "kind": "material",
        "name": "قنينة بلاستيك نظيفة",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": "٥٠٠ مل حتى ٢ لتر."
      },
      {
        "id": "tool-self-watering-planter-3",
        "kind": "material",
        "name": "شريط قماش قطني (من تيشيرت قديم)",
        "imageUrl": "",
        "quantity": "حسب المخطّط",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-self-watering-planter-4",
        "kind": "material",
        "name": "تراب زراعة",
        "imageUrl": "",
        "quantity": "كوب إلى كوبين",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-self-watering-planter-5",
        "kind": "material",
        "name": "نبتة صغيرة أو بذور",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-self-watering-planter-6",
        "kind": "material",
        "name": "شريط لاصق",
        "imageUrl": "",
        "quantity": "١",
        "optional": true,
        "note": "لتغطية الحافة."
      }
    ],
    "steps": [
      {
        "stepNumber": 1,
        "title": "نظّف القنينة",
        "instruction": "انزع الملصق، واغسل القنينة والغطا بالماء، وخلّيها تنشف تماماً.",
        "op": "clean",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 2,
        "title": "علّم خط القصّ",
        "instruction": "بالمسطرة، علّم خطاً دائرياً حوالين القنينة عند الارتفاع المبيّن بالمخطّط.",
        "op": "mark-cut",
        "measure": "planter-cut",
        "tip": "سنّد القلم على كومة كتب ودوّر القنينة ليطلع الخط مستقيماً.",
        "warning": ""
      },
      {
        "stepNumber": 3,
        "title": "اقصّ القنينة نصّين",
        "instruction": "شخص كبير يقصّ على الخط بالضبط. بيصير جزء علوي (بالغطا) وجزء سفلي.",
        "op": "cut",
        "measure": "planter-cut",
        "tip": "",
        "warning": "القصّ للكبار بس."
      },
      {
        "stepNumber": 4,
        "title": "أمّن الحافة",
        "instruction": "غطِّ حافة القصّ على القطعتين بشريط لاصق حتى ما تجرح.",
        "op": "seal-edge",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 5,
        "title": "ركّب الفتيل",
        "instruction": "اقصّ شريط القماش بالمقاس المبيّن، ومرّره من فتحة الغطا: نصفه داخل الجزء العلوي، ونصفه متدلٍّ تحت.",
        "op": "wick",
        "measure": "planter-wick",
        "tip": "إذا الفتحة صغيرة، افتح الغطا واعمل فيه ثقب ٥ ملّي بمسمار.",
        "warning": ""
      },
      {
        "stepNumber": 6,
        "title": "اقلب الجزء العلوي داخل السفلي",
        "instruction": "اقلب الجزء العلوي رأساً على عقب (الغطا للتحت) وحطّه داخل الجزء السفلي مثل القمع.",
        "op": "nest",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 7,
        "title": "حطّ التراب والنبتة",
        "instruction": "عبّي الجزء العلوي تراباً، وامسك الفتيل حتى ما ينطمّ، بعدين ازرع البذور أو النبتة.",
        "op": "fill-soil",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 8,
        "title": "عبّي الخزّان",
        "instruction": "ارفع الجزء العلوي وصبّ الماء في الجزء السفلي حتى الارتفاع المبيّن، بعدين رجّع الجزء العلوي مكانه.",
        "op": "fill-water",
        "measure": "planter-fill",
        "tip": "زوّد الماء كل كم يوم لمّا يقلّ.",
        "warning": ""
      }
    ],
    "variantKeys": [
      "pet-water-500ml",
      "pet-water-600ml",
      "pet-sports-750ml",
      "pet-water-1000ml",
      "pet-water-1500ml",
      "pet-soda-2000ml"
    ]
  },
  {
    "id": "idea-bird-feeder",
    "slug": "bird-feeder",
    "title": "مطعم عصافير بالملاعق",
    "summary": "قنينة معلّقة، تمرّ فيها ملعقتان خشب كمسند، وفوق كل ملعقة فتحة صغيرة يطلع منها الحَب لمّا يقف العصفور.",
    "difficulty": "easy",
    "estimatedMinutes": 25,
    "minAge": 7,
    "safetyNotes": "الثقوب يعملها شخص كبير. علّقه بمكان بعيد عن القطط.",
    "source": "طريقة الملاعق الخشبية الشائعة (Instructables)",
    "thumbnailUrl": "media/ideas/bird-feeder-thumb.svg",
    "finalImageUrl": "media/ideas/bird-feeder-final.svg",
    "model3dUrl": "",
    "model3dPreviewUrl": "",
    "tools": [
      {
        "id": "tool-bird-feeder-0",
        "kind": "tool",
        "name": "سكين ورق",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": "للثقوب — بيد شخص كبير."
      },
      {
        "id": "tool-bird-feeder-1",
        "kind": "tool",
        "name": "قلم تحديد ومسطرة",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-bird-feeder-2",
        "kind": "material",
        "name": "قنينة نظيفة مع غطاها",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": "١ لتر حتى ٢ لتر."
      },
      {
        "id": "tool-bird-feeder-3",
        "kind": "material",
        "name": "ملعقتان خشب طويلتان",
        "imageUrl": "",
        "quantity": "٢",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-bird-feeder-4",
        "kind": "material",
        "name": "خيط أو دوبارة",
        "imageUrl": "",
        "quantity": "٤٠ سم",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-bird-feeder-5",
        "kind": "material",
        "name": "حَب عصافير",
        "imageUrl": "",
        "quantity": "كوب",
        "optional": false,
        "note": ""
      }
    ],
    "steps": [
      {
        "stepNumber": 1,
        "title": "نظّف القنينة ونشّفها",
        "instruction": "اغسل القنينة والغطا، انزع الملصق، وخلّيها تنشف تماماً.",
        "op": "clean",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 2,
        "title": "علّم مكان الملعقة الأولى",
        "instruction": "على جهتين متقابلتين، علّم نقطتين على الارتفاع المبيّن بالمخطّط.",
        "op": "mark-holes",
        "measure": "feeder-perch1",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 3,
        "title": "مرّر الملعقة الأولى",
        "instruction": "شخص كبير يعمل ثقبين صغيرين مكان العلامتين، ثم مرّر ملعقة الخشب حتى تطلع من الجهتين بالتساوي.",
        "op": "rod",
        "measure": "feeder-perch1",
        "tip": "",
        "warning": "الثقوب للكبار بس."
      },
      {
        "stepNumber": 4,
        "title": "مرّر الملعقة الثانية",
        "instruction": "علّم ثقبين آخرين فوق الأولى بالمسافة المبيّنة وبزاوية ربع دورة، ومرّر الملعقة الثانية.",
        "op": "rod",
        "measure": "feeder-perch2",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 5,
        "title": "افتح منافذ الحَب",
        "instruction": "فوق رأس كل ملعقة مباشرة، وسّع الثقب إلى فتحة بالقياس المبيّن ليخرج منها الحَب.",
        "op": "window",
        "measure": "feeder-opening",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 6,
        "title": "اعمل معلاقة",
        "instruction": "اعمل ثقبين صغيرين على جهتين قرب الغطا، مرّر خيط ٤٠ سم، واعمل عروة.",
        "op": "hanger",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 7,
        "title": "عبّي الحَب",
        "instruction": "صبّ حَب العصافير جوّا القنينة من فوق، وسكّر الغطا.",
        "op": "fill-seed",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 8,
        "title": "علّقه",
        "instruction": "علّق المطعم بغصن شجرة، بمكان تقدر تشوفه من الشبّاك وبعيد عن القطط.",
        "op": "use-hang",
        "measure": "",
        "tip": "",
        "warning": ""
      }
    ],
    "variantKeys": [
      "pet-water-1000ml",
      "pet-oil-1000ml",
      "pet-water-1500ml",
      "pet-soda-2000ml",
      "pet-juice-1000ml"
    ]
  },
  {
    "id": "idea-coin-bank",
    "slug": "coin-bank",
    "title": "حصّالة نقود",
    "summary": "قنينة كاملة فيها شقّ ضيّق على جنبها تنزّل منه القروش، وتفرّغها بفتح الغطا.",
    "difficulty": "easy",
    "estimatedMinutes": 15,
    "minAge": 6,
    "safetyNotes": "شقّ النقود يعمله شخص كبير.",
    "source": "الطريقة الشائعة (NOAA · All Free Crafts)",
    "thumbnailUrl": "media/ideas/coin-bank-thumb.svg",
    "finalImageUrl": "media/ideas/coin-bank-final.svg",
    "model3dUrl": "",
    "model3dPreviewUrl": "",
    "tools": [
      {
        "id": "tool-coin-bank-0",
        "kind": "tool",
        "name": "سكين ورق",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": "للشقّ — بيد شخص كبير."
      },
      {
        "id": "tool-coin-bank-1",
        "kind": "tool",
        "name": "قلم تحديد ومسطرة",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-coin-bank-2",
        "kind": "material",
        "name": "قنينة نظيفة مع غطاها",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-coin-bank-3",
        "kind": "material",
        "name": "ورق ملوّن ولاصق، أو دهان",
        "imageUrl": "",
        "quantity": "١",
        "optional": true,
        "note": "للتزيين."
      }
    ],
    "steps": [
      {
        "stepNumber": 1,
        "title": "نظّف القنينة ونشّفها",
        "instruction": "اغسل القنينة والغطا، انزع الملصق، ونشّفها. خلّي الغطا مسكّراً.",
        "op": "clean",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 2,
        "title": "علّم الشقّ",
        "instruction": "ضع القنينة على جنبها، وعلّم مستطيلاً رفيعاً على الجهة اللي لفوق بالمقاس المبيّن.",
        "op": "mark-slot",
        "measure": "bank-slot",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 3,
        "title": "اقصّ الشقّ",
        "instruction": "شخص كبير يقصّ على المستطيل بسكين الورق ليصير شقّاً.",
        "op": "slot",
        "measure": "bank-slot",
        "tip": "",
        "warning": "القصّ للكبار بس."
      },
      {
        "stepNumber": 4,
        "title": "جرّب قرشاً",
        "instruction": "جرّب تدخّل أكبر قرش من الشقّ. إذا كان ضيّقاً، وسّعه ١–٢ ملّي فقط.",
        "op": "coin-test",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 5,
        "title": "زيّنها",
        "instruction": "لفّ القنينة بورق ملوّن أو ادهنها، وخلّي الشقّ مكشوفاً.",
        "op": "decorate",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 6,
        "title": "ابدأ توفّر",
        "instruction": "نزّل القروش من الشقّ. لتفريغها، افتح الغطا فقط.",
        "op": "use-coins",
        "measure": "",
        "tip": "",
        "warning": ""
      }
    ],
    "variantKeys": [
      "pet-water-500ml",
      "pet-water-600ml",
      "pet-water-1000ml",
      "pet-water-1500ml",
      "pet-oil-1000ml"
    ]
  },
  {
    "id": "idea-pen-pot-organizer",
    "slug": "pen-pot-organizer",
    "title": "علبة أقلام للمكتب",
    "summary": "قاع القنينة ينقصّ ليصير علبة تحمل الأقلام والمقص على المكتب.",
    "difficulty": "easy",
    "estimatedMinutes": 15,
    "minAge": 6,
    "safetyNotes": "القصّ يعمله شخص كبير. أمّن الحافة بطيّها للخارج أو بشريط.",
    "source": "الطريقة الشائعة (wikiHow · The Spruce Crafts)",
    "thumbnailUrl": "media/ideas/pen-pot-organizer-thumb.svg",
    "finalImageUrl": "media/ideas/pen-pot-organizer-final.svg",
    "model3dUrl": "",
    "model3dPreviewUrl": "",
    "tools": [
      {
        "id": "tool-pen-pot-organizer-0",
        "kind": "tool",
        "name": "مقص أو سكين ورق",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": "للقصّ — بيد شخص كبير."
      },
      {
        "id": "tool-pen-pot-organizer-1",
        "kind": "tool",
        "name": "قلم تحديد ومسطرة",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": ""
      },
      {
        "id": "tool-pen-pot-organizer-2",
        "kind": "material",
        "name": "قنينة بلاستيك نظيفة",
        "imageUrl": "",
        "quantity": "١",
        "optional": false,
        "note": "٥٠٠ مل حتى ١ لتر."
      },
      {
        "id": "tool-pen-pot-organizer-3",
        "kind": "material",
        "name": "شريط ملوّن أو دهان",
        "imageUrl": "",
        "quantity": "١",
        "optional": true,
        "note": ""
      }
    ],
    "steps": [
      {
        "stepNumber": 1,
        "title": "نظّف القنينة",
        "instruction": "اغسل القنينة، انزع الملصق، ونشّفها.",
        "op": "clean",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 2,
        "title": "حدّد الارتفاع",
        "instruction": "حطّ أطول قلم عندك جنب القنينة، وعلّم خطاً دائرياً على الارتفاع المبيّن بالمخطّط.",
        "op": "mark-cut",
        "measure": "pen-height",
        "tip": "دوّر القنينة على قلم ثابت ليطلع الخط منظّماً.",
        "warning": ""
      },
      {
        "stepNumber": 3,
        "title": "اقصّ الجزء العلوي",
        "instruction": "شخص كبير يقصّ على الخط بالضبط. احتفظ بالجزء السفلي.",
        "op": "cut-bottom",
        "measure": "pen-height",
        "tip": "",
        "warning": "القصّ للكبار بس."
      },
      {
        "stepNumber": 4,
        "title": "أمّن الحافة",
        "instruction": "اطوِ الحافة المقصوصة للخارج، أو غطّيها بشريط لاصق.",
        "op": "seal-edge",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 5,
        "title": "ثقب تصريف (اختياري)",
        "instruction": "إذا رح توقّف فيها فُرَشاً رطبة، اعمل ثقباً صغيراً بالقاع ليخرج الماء.",
        "op": "base-hole",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 6,
        "title": "زيّنها",
        "instruction": "لفّ العلبة بشريط ملوّن أو ادهنها وخلّيها تنشف.",
        "op": "decorate",
        "measure": "",
        "tip": "",
        "warning": ""
      },
      {
        "stepNumber": 7,
        "title": "استعملها",
        "instruction": "وقّف أقلامك وأدواتك جوّاها على المكتب.",
        "op": "use-pens",
        "measure": "",
        "tip": "",
        "warning": ""
      }
    ],
    "variantKeys": [
      "pet-water-500ml",
      "pet-water-600ml",
      "pet-sports-750ml",
      "pet-water-1000ml",
      "pet-oil-1000ml"
    ]
  }
];
